### ISSUE TITLE
Ch02. The Production Environment at Google, from the Viewpoint of an SRE

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/site-reliability-engineering#1]

**Comment by hhhyunwoo** [comment]
## Hardware

- 구글의 대부분의 컴퓨터 자원은 구글이 전원 공급, 냉각 기능, 네트워크 및 컴퓨터 하드웨어 등을 `모두 직접 디자인한 데이터센터`에 있음
- **Machine**
    - 하드웨어 (or VM) 을 의미
- **Server**
    - 서비스를 구현하는 소프트웨어를 의미

![image](https://github.com/hhhyunwoo/hhhyunwoo/assets/37402136/617541b0-caa6-4eb4-8874-253e09369cef)

- 구글 데이터센터의 Toplogy
    - 수십 대의 머신이 랙에 장착되어있음
    - 랙은 일렬로 늘어서 있음
    - 하나 또는 여러 랙이 클러스터를 구성
    - 데이터 센터 선물 내에는 여러 개의 클러스터가 있음
    - 근거리의 여러 DC 건물이 모여 캠퍼스를 이룸

## Hardware를 조율하는 시스템 소프트웨어

### 머신 관리하기

![image](https://github.com/hhhyunwoo/hhhyunwoo/assets/37402136/e9c6b532-b6dd-4809-807b-a00244bb0cfd)

- **Borg**
    - `Large-scale cluster management at Google with Borg`
        - https://research.google/pubs/pub43438/
        - Kubernetes의 전신
    - Apache Mesos와 유사한 분산 클러스터 운영 시스템
    - 해당 시스템을 이용해서 머신을 관리함
        - BNS (Borg Naming Service), 리소스 할당 등등..

### Storage

![image](https://github.com/hhhyunwoo/hhhyunwoo/assets/37402136/f74e2ff1-d090-4a73-acf1-4bf221f4711e)

1. 가장 낮은 `D 계층`은 클러스터 내의 거의 모든 머신이 실행하는 파일 서버.
2. D 계층 위의 `Colossus` 는 **GFS**(Google File System)의 후속 제품으로서 전통적인 파일 시스템처렁 동작하며 복제와 암호화까지 지원
3. DB와 유사한 서비스들
    1. **Bigtable** : 페타바이트 크기의 DB를 처리할 수 있는 NoSQL. 데이터가 분산되어 영구적으로 저장됨. Eventually Consistent 한 DB
    2. **Spanner** : 실시간 일관성이 있어야 하는 곳에 SQL 인터페이스 제공 
    3. **Blobstore** : 대량의 비정형 데이터를 저장할 수 있음 

### Networking

- `Bandwidth Enforcer` (BwE)
    - 가용 대역폭을 관리해서 평균 가용 대역폭을 극대화 함
- `GSLB` (Global Software Load Balancer)
    - DNS 요청에 대한 지역 로드밸런싱 수행
    - 사용자 서비스 수준에서의 로드밸런싱 수행
    - RPC 수준에서의 로드밸런싱

## 기타 시스템 소프트웨어

### 잠금 서비스

- **Chubby**
    - 분산 Lock 시스템으로 분산된 서버들 사이에서 발생할 수 있는 자원 공유 문제 해결
    - Paxos 프로토콜 사용
        - Consensus Algorithm
        - RAFT

### 모니터링과 알림

- **Borgmon**
    - `모니터링`하는 서버들로부터 다양한 지표들을 수집

## 소프트웨어 인프라스트럭쳐

구글의 소프트웨어 아키텍처는 하드웨어 인프라를 최대한 효과적으로 활용할 수 있도록 디자인됨.

- **Stubby**
    - 내부 `RPC 통신`을 위해 만든 시스템
    - 오픈 소스로 gRPC를 만듬
    - RPC (Remote Procedure Call)
        - RPC 간의 데이터 전송은 Protocl Buffers 를 이용함.
        - Protobufs 는 Apache의 Thrift와 유사
        - Protobufs 는 XML 을 이용해 구조화된 데이터를 직렬화하는 방식에 비해 더 많은 장점을 제공.
        - 사용하기 더 쉽고, 크기가 3~10배 더 작고, 20~100배 더 빠르고 명료함

## Reference

- https://sre.google/sre-book/table-of-contents/

**Comment by jjangsungwon** [comment]
[블로그 포스팅](https://jjangsungwon.tistory.com/166)으로 대체하겠습니다~!

**Comment by ChanhuiSeok** [comment]
# CH1. SRE 신조

가용성, 응답 시간, 성능, 효율성, 변화 관리, 모니터링, 위기 대응, 수용량 계획에 대한 책임을 지고 있음.

- 지속적으로 엔지니어링에 집중
  - SRE가 운영 업무에 투입하는 시간은 최대 50%로, 나머지는 코딩 기술로 프로젝트 업무 수행
  - 포스트모텀 → 검시 한다는 의미인데 여기서는 장애 조사 후 상세 내용, 원인, 해결하기 위해 했던 행동, 대응 방안 등의 도출을 하는 문화를 말한다. (구글은 이미 이게 문화로 정착되어 있음)
- 서비스 안정성을 유지하면서 변화를 최대한 수용
    - 에러 예산 개념 도입 → 모든 것에 신뢰성 목표를 100%로 잘못 설정하는 것에서 유래
    - 만약 서비스의 목표 가용성(신뢰성) 이 99.99%이면, 불가용 상태는 0.01%이고, 이것이 필연적으로 발생할 수밖에 없는 서비스의 에러 예산임
    - 에러 예산은 SRE가 새로운 기능들을 빠르게 출시하기 위해 감수해야 할 모든 위험을 처리하는 데 투입하는 것이 이상적이다. 에러 예산이 도입되면, 더 이상 SRE들은 ‘무정지 시스템’ 같은 목표를 세우지 않고, SRE팀과 제품 개발팀이 기능의 출시 속도를 극대화하고자 에러 예산을 활용하는 것에 집중하게 됨
    - 시스템이 정지하더라도 장애 상황으로만 여기지 않고 혁신의 과정에서 어쩔 수 없이 발생하는 예측 가능한 상황이 됨
- 모니터링
    - 최우선 수단 중 하나. 계속해서 시스템의 상태와 가용성을 점검한다.
    - **장애에 관한 판단은 소프트웨어가 대신하고, 반드시 어떤 대응이 필요한 경우에만 사람에게 알림이 도착해야 한다. 
- 긴급 대응
    - 구글은 긴급 대응에 대한 행동 지침을 바탕으로, 엔지니어들이 장애 상황에 대응할 수 있게 추첨을 통해 훈련을 지속하고 있음
- 변화 관리
    - SRE는 70% 정도의 장애 상황이 서비스 중인 시스템의 변화 때문에 발생한다는 점을 발견했음
    - 자동화를 통해 ‘제품의 단계적 출시’, ‘문제를 빠르고 정확하게 도출’, **‘문제 발생 시 안전하게 이전 버전으로 되돌리기’** 를 이루어내야 한다.
- 수요 예측과 수용 계획
    - 미래 수요 대비, 필요 가용성을 제공할 수 있는 충분한 수용력과 여력을 확보하기 위함
- 프로비저닝
    - 변화 관리와 수용 계획을 합한 개념. (구글링 : 사용자 혹은 비지니스 요구사항에 맞게 할당, 배치, 배포하여 시스템을 사용가능하도록 준비하는 절차) 꼭 필요한 시점에 최대한 빠르게 수행되어야 함
- 효율성과 성능

# CH2 SRE 관점에서 바라본 구글의 프로덕션 환경

## 구글 데이터센터의 토폴로지
- 수십 대의 머신이 랙에 장착, 랙은 일렬로 늘어서 있고, 하나 또는 여러 랙이 클러스터를 구성
- 통상 데이터센터 건물 내에 여러 클러스터가 갖춰져 있음
- 근거리의 여러 데이터센터 건물이 모여 캠퍼스를 이룸

## 하드웨어를 조율하는 시스템 소프트웨어
- 엄청난 규모의 하드웨어를 조정할 수 있는 소프트웨어에 의해 제어 및 관리되어야 함

### (1) 머신 관리
- 보그(에 대한 예시가 나오는데 후속 작품이 쿠버네티스라고 한다.)
    - 사용자의 잡 실행 역할을 담당, 새로운 잡 실행 시 태스크 수행할 머신 탐색 후, 해당 머신에게 서버 프로그램을 실행할 것을 요청 → 태스크들의 실행 지속 모니터링

### (2) 저장소
- 러스터(Lustre), 하둡 분산 파일 시스템(Hadoop) 활용
    - 사용자에게 클러스터 환경에서 쉽고 안정적으로 활용할 수 있는 저장소를 제공하는 것이 목적
- D계층 → 콜로서스 계층 → 여기에 콜로서스를 바탕으로 데이터베이스와 유사한 서비스들 존재(빅테이블, 스패너, 블롭스토어)

### (3) 네트워킹
- 구글은 다양한 방법으로 네트워크 하드웨어를 관리하는 중임.
- 세계에 퍼져있는 서비스 간의 지연 응답을 최소화하고자 사용자를 가장 가까운 데이터센터로 연결해 준다.
    - 글로벌 로드밸런서 → DNS 요청에 대한 지역적 로드밸런싱, 사용자 서비스 수준에서의 로드밸런싱, 원격 프로시저 호출 수준에서의 로드밸런싱

## 기타 시스템 소프트웨어

### (1) 잠금 서비스
- 처비(Chubby) 잠금 서비스 : 잠금을 관리하는 파일 시스템과 유사한 API 제공. 처비는 잠금들을 여러 지역의 데이터센터에 걸쳐 관리한다.
    - 비동기 합의를 위해 팍소스 프로토콜 사용
    - 마스터 노드를 결정하는 데 중요한 역할을 담당
    - 처비에 저장될 데이터는 일관성을 확보해야 하는 데이터가 적합

### (2) 모니터링과 알림
- 보그몬 모니터링 프로그램 인스턴스를 실행하여 다양한 지표들을 수집한다.

## 소프트웨어 인프라스트럭처
- 구글 소프트웨어 아키텍처는 하드웨어 인프라스트럭처를 최대한 효과적으로 활용할 수 있도록 디자인됨
- 구글의 모든 서비스는 스튜비 라는 RPC 인프라스트럭처를 이용해 통신함
- 서버는 FE로부터 RPC 요청을 받아 백엔드로 RPC 호출들을 보낸다.
- 프로토콜 버퍼 : RPC 간의 데이터 전송을 할 때 활용하는 것. (https://protobuf.dev/)

## 개발 환경
- 개발 속도는 구글에서 매우 중요한 개념이다.
- 안드로이드, 크롬을 제외하고 구글 소프트웨어 엔지니어들은 하나의 공유 저장소를 바탕으로 업무를 수행한다.
    - 프로젝트 외부 컴포넌트에서 문제 발생 → 엔지니어는 문제 해결 → 변경 사항을 소유자에게 보내 리뷰 요청 → 변경된 코드 제출
    - 소스 코드 변경은 반드시 리뷰를 거쳐야 한다. 모든 소프트웨어는 제출 전 리뷰를 받아야 한다.
    - 일부 프로젝트는 테스트를 통과하면 자동으로 새 버전의 소프트웨어가 프로덕션 환경으로 배포되는 `푸시-온-그린` 시스템을 채택 중
