### ISSUE TITLE
Ch23

### ISSUE THREAD

**Issue by jjangsungwon** [WhiteKow/site-reliability-engineering#10]

**Comment by ChanhuiSeok** [comment]
# 치명적인 상태 관리 - 신뢰성 위한 분산에 대한 합의

- 신뢰할 수 있는 고가용성 시스템을 효과적으로 구축하려면 → 분산에 대한 합의 필요
- 전통적인 ACID(원자성, 영속성, 격리성, 내구성) 데이터 저장소에 익숙 / 계속해서 성장하는 분산 데이터 저장소 기법들은 BASE(기본적인 가용성, 유연한 상태, 궁극적 일관성) 이라는 조금 다른 의미들을 제공함.
    - 특정 종류의 데이터를 다루는 애플리케이션에 적합
    - 더 많은 비용이 필요한 대용량 데이터와 트랜잭션 처리
    - 쓰기 작업을 여러 프로세스에서 동시 수행 가능
    - 충돌을 해결하기 위한 메커니즘 제공
    - 개발자 입장에선 BASE 개념만을 지원하는 데이터 저장소 이용한 시스템을 잘 디자인하기 더 어려운 편.

## 합의가 필요한 이유

- 분산 시스템 → 복잡, 문제 해결 난해, … → 장애 시 동작으로 놀라는 일을 빈번히 겪게 됨
- 사례 연구 1 : 분리된 뇌 문제
    - 하나의 리더 - 하나의 수행 서버로 구성 / 자신의 파트너와 연결할 수 없는 상태가 되면 STONITH(다른 노드 강제 종료) 명령을 파트너 노드에 전달 → 노드 강제 종료 → 그 파일에 대한 소유권 차지. → 뇌가 분리된 인스턴스 (그러니까 하나의 짝으로 움직여야 한다는 의미인 듯) 들이 생겨나는 경우를 낮추기 위함임
    - 이 때 일부 명령이 노드에 전달되지 않으면, 각자가 모두 소유권을 가진다고 생각하거나 양쪽 모두 STONITH 명령을 보내서 둘 다 종료되면 → 데이터가 망가지거나 사용이 불가능해지는 것이다.
    - 이 시스템의 문제 : 단순한 타임아웃으로 리더 선출 문제를 해결하려고 했다는 점. 단순한 건강 상태 점검만으로는 해결할 수 없음
- 사례 연구 2 : 사람이 개입해야 하는 장애 조치
    - (추가로 조사) 샤딩 : 대용량 데이터베이스를 효율적으로 처리하기 위해 데이터를 물리적으로 분산저장하는 기술 이라는 것을 알게 됨. (샤딩은 데이터를 여러 데이터베이스 인스턴스로 분할 / 파티셔닝은 한 데이터베이스 인스턴스에서 데이터를 분할)
    - 주 샤드와 차선 샤드 → 건강 상태 판단 불가능하면 사례 1처럼 분리된 뇌 시나리오를 피하고자 사람에게 문제 해결 요청 → 데이터 가용성에 매우 좋지 않고 시스템 운영 엔지니어들의 운영 업무가 불필요하게 증가되고, 사람의 개입은 기본적으로 시스템 확장성을 떨어뜨림.
- 사례 연구 3 : 그룹-멤버십 알고리즘 오류

이처럼 여러 문제들로 인해 여러 가지 버전의 분산에 대한 합의가 필요해짐.

## 분산에 대한 합의가 동작하는 방식

- 충돌-실패 혹은 충돌-복구 방식 사용
    - 대부분은 본질적으로 느린 네트워크, 시스템 재시작 등에 대한 일시적 현상이라 충돌-복구 알고리즘이 훨씬 유용함.
    - 비잔틴 실패와 논비잔틴 실패
    - 분산 합의 문제에 대한 최초 해결책 → 램포트, 팍소스 → 그 외에도 여러 프로토콜들이 존재
- Paxos 프로토콜 : 시스템 내 대부분의 프로세스가 받아들이거나, 받아들이지 못하는 일련의 제안들을 처리. 어떤 제안이 안 받아들여졌다 → 그대로 실패한다.
    - 이 자체로는 그닥 유용하지 않음

분산 합의를 위한 시스템 아키텍처 패턴

- 분산 합의 알고리즘 → 저수준, 원시적임. 노드의 집합이 어느 한 값에 단 한번만 동의하는 것을 허용할 뿐
- 주키퍼, 콘솔(Consul), etcd → 분산 합의 알고리즘을 구현하는 서비스 클라이언트 / 분산 처리 프로그램의 분산 코디네이션 서비스 라고 한다.. (구글은 처비)
- 신뢰할 수 있는 복제된 상태 머신
    - RSM : 복제된 상태 머신 → 여러 프로세스를 통해 동일한 작업을 동일한 순서로 실행하는 시스템. 데이터, 설정 저장소, 잠금, 리더 선출 등 유용한 분산 시스템 컴포넌트와 서비스 구축을 위한 기본적인 단위
- 신뢰할 수 있는 복제된 데이터 저장소와 설정 저장소
- 리더 선출을 이요한 고가용성 프로세싱
- 분산 조정과 잠금 서비스
    - Map 단계 - Reduce 단계 : **장벽**을 활용해, Map 단계가 모두 완료되기 전에는 Reduce 단계 연산이 수행되지 않게 함. 장벽은 RSM으로 구현 가능
    - 잠금 → RSM으로 구현 가능한 또 다른 형태의 조정 요소.
- 신뢰할 수 있는 분산 큐와 메시지
    - 큐를 RSM으로 구축하여 더 견고하게 구축

## 분산 합의의 성능

- 분산 알고리즘 성능을 향상시킬 수 있는 다양한 방법들 존재. 구글도 주요 시스템들의 핵심이고, 실제로 매우 효율적으로 운영할 수 있음을 증명하고 있다.
    - Multi-Paxos 프로토콜
    - Fast Paxos 프로토콜

## 분산 합의 시스템 모니터링

- 중요 프로덕션 시스템들은 모니터링 필요. 분산 합의 시스템에 대한 아래와 같은 특별한 관심이 좀 더 필요하다.
    - 각 합의 그룹 내에서 실행 중인 멤버 수와 각 프로세스 건강 상태
    - 지속적으로 지연이 발생하는 복제 서버
    - 리더 존재 여부
        - Multi-Paxos 같은 프로토콜 기반은 리더가 없어질 경우 시스템 동작이 완전히 멈추므로 반드시 리더  존재 여부를 모니터링 해야 함
    - 리더 변경 횟수
        - 빈번한 변화는 시스템 성능에 부정적 영향 미침
    - 합의 트랜잭션 횟수
        - 시스템이 정상이라면 시간이 지나면서 합의 트랜잭션 수가 계속 증가하는 것을 볼 수 있어야 함
    - 확인된 제안의 횟수 및 합의된 제안의 횟수
    - 처리량과 지연응답

**Comment by hhhyunwoo** [comment]
# 23장 치명적인 상태관리하기: 신뢰성을 위한 분산에 대한 합의

- ACID 개념
    - Atmoicity, Consistency, Isolation, Durability
- BASE 개념
    - Basically Available, Soft state and Eventual consistency

# 합의는 왜 필요할까

## Split brain problem

- 하나의 리더와 하나의 수행 서버가 있을 때, 분리되는 경우

## 사람이 개입해야하는 장애 조치

## 그룹-멤버십 알고리즘의 오류

# 분산 합의를 위한 시스템 아키텍처 패턴

## 신뢰할 수 있는 복제된 상태머신

- Replicated State Machine
- RSM을 통해서 메시지를 복제해서 관리함

## 신뢰할 수 있는 복제된 데이터 저장소와 설정 저장소

- Reliable Replicated Datastore 는 복제된 상태 머신 애플리케이션

## 리더 선출을 이용한 고가용성 프로세싱

## Coordination 과 잠금 서비스

- Barrier 를 통해서 모든 부분이 첫 단계 연산이 완료되어야 한다는 조건을 만족할 때까지 프로세스의 그룹이 작업을 수행하지 못하도록 하는 기본 적인 요소.
- 이를 통해 Map 과 Reduce 단계에서 barrier 를 사용할 수 있음

## 신뢰할 수 있는 분산 큐와 메시지

- 큐를 RSM으로 구축하면 견고함

# 분산 합의의 성능

- 합의 알고리즘은 느리고, 높은 쓰루풋과 낮은 레이턴시를 요구하는 시스템에서 사용하기에는 비용이 너무 많이든다.
- Locality 가 중요함. 멀수록 Round trip time 이 오래 걸린다.

## 읽기 작업 부하의 확장

- 일반적으로 읽기에 더 많은 작업을 수행함. 따라서 부하 확장이 중요함.
- Compare and Set 이라는 비교 후 저장을 사용해서 일관성을 유지할 수도 있음.

## 과반수 임대

- 복제된 서버의 과반수에 복제된 데이터 저장소의 상태의 일부에 대한 읽기 작업을 임대하는 방법.
- 읽기 작업이 많은 부하에 특히 유용함.

**Comment by jjangsungwon** [comment]
[치명적인 상태 관리하기: 신뢰성을 위한 분산에 대한 합의](https://jjangsungwon.tistory.com/194)
