### ISSUE TITLE
Ch27, 29

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/site-reliability-engineering#11]

**Comment by hhhyunwoo** [comment]
# 27장. 대용량 환경에서의 신뢰할 수 있는 제품 출시.

### LCE 팀 (Launch Coordination Engineers)

- 제품의 출시에 합류한 각기 다른 엔지니어링 그룹 간의 조율을 위해 만들어진 특별한 팀
- 제품의 출시 과정에서 다양한 문제들을 조율함

## 출시 조율 엔지니어링

- 구글의 신뢰성 표준과 모범 사례즐 준수하도록 감사하고 도움을 줌
- 안전하게 출시할 수 있도록 통제원 역할을 수행

### 역할

- 경험의 전파.
- 교차 기능으로 여러 팀간의 업무 관점에서 바라봄
- 객관성

## 출시 절차 마련하기

- 경량
- 견고함
- 주도면밀함
- 확장성
- 순응성
- 간결성
- 직접 부딪히기
- 빠른 공통 경로

위와 같은 절차를 바탕으로 집중과 간소화 진행 / 예상치 못한 제품의 출시 방지 / 확인목록 개발 / 수용량 계획 / 장애 모드 확인 / 클라이언트 동작 확인 / 절차와 자동화 수행 / 배포 절차 수립 수행 / 외부 의존성 확인 등을 수행함 

# 29장. 방해 요소에 대한 대처

어떻게 방해 요소를 대처하면서 효율적으로 일을 할 것인가에 대한 내용

## 불완전한 머신

- 인간은 불완전하며 방해요소들을 처리하고 인지적 몰입 상태(Flow state)를 오래, 쉽게 가져가야함.
- 그렇게 하기 위해서는 방해 요소를 관리해야한다.
- → 창의력과 몰두가 뛰어나짐

## 한 가지 일을 잘 해내기

- 산만한 주변 환경 정리
- 시간을 잘 나누어 쓰기

## 그래서 우리가 해야할 일은?

- 업무의 무게를 확인하고 나누어서 잘 처리하자

### 비상 대기

- 그 사람은 프로젝트에서 빼자

### 티켓

- 라운드 로빈이 아니라, 업무 맡을 사람을 딱 정하자

### 진행 중인 업무

- 누구라도 책임을 맡을 수 있는 역할을 가능한 많이 만들자

## 방해 요소 줄이기

### 티켓을 실제로 분석하자

- 티켓 회전을 잘 하도록 해야함
- 아무나 던지지 말고, 어떻게 방해요소를 줄이면서 티켓을 뿌릴 것인지 생각하자

**Comment by jjangsungwon** [comment]
블로그 포스팅으로 대체합니다~!
- [27장](https://jjangsungwon.tistory.com/195)
- [29장](https://jjangsungwon.tistory.com/196)

**Comment by ChanhuiSeok** [comment]
### 27장 : 대용량 환경에서의 신뢰할 수 있는 제품 출시

- 제품의 출시 : 외부에 노출되는 새로운 코드를 수반하는 애플리케이션의 변화.
- 출시 조율 엔지니어링 (SRE 내에 있는 LCE)
    - 일종의 컨설팅팀, 제품 출시 절차 순조롭게 진행되도록 도와줌
    - 제품의 서비스 감사, 신뢰성 향상 위한 도움을 줌
    - 기술적 관점 주도, 안전한 출시 위한 통제원 역할 수행 등…
    - (→ …)
- 출시 절차 마련하기
    - 구글이 10년 이상 출시 절차를 연마해 오면서, 성공적인 출시 절차를 특징짓는 몇 가지 조건을 확인했음.
        - 경량, 견고함, 주도면밀함, 확장성, 순응성, 간결성, 직접 부딪히기, 빠른 공통 경로
    - 구글의 거의 모든 그룹 → 공용 인프라스트럭처로의 집중 유도하는 공통된 출시 절차에 참가함. (기존의 인프라스트럭처를 빌딩 블록처럼 사용할 것을 권장) → 집중, 간소화
- 출시 확인목록 개발하기
    - 확인목록 → 새로운 서비스와 재품을 재현 가능한 신뢰성 바탕으로 출시하기 위한 수단
    - LCE 팀이 오랜 시간 동안 정기적으로 관리하며 숙성시켜온 것임
    - 아키텍처와 의존성, 통합, 수용량 계획, 장애 모드, 클라이언트 동작, 절차와 자동화, 배포 절차, 외부 의존성, 발표 계획 등에 있어서 확인목록 질문들과 실행 항목을 정의하여 관리하고 있다.
    - 배포 절차 → 대부분의 개발 작업을 주 브랜치에서 진행, 릴리즈는 각 릴리즈별로 별개의 브랜치에서 빌드 → 주 브랜치에서 관련이 없는 변경 사항을 가져오는 일 없이 특정 릴리즈의 버그만 손쉽게 수정 가능 … (여기에 대해 궁금)
- 안정적인 출시를 위한 기법들
    - 점진적, 단계적 출시
    - 과부하시의 동작과 부하 테스트
        - 서비스 과부하 시 어떻게 반응하는지 처음부터 예측하는 건 매우 어려우므로 부하 테스트는 가치 있는 도구이고, 제품 출시에 부하 테스트가 필요하다.
- 출시 엔지니어들의 컨설팅 세션 → 출시 리뷰라고 부름. 구글에서 새 제품 출시 전에 수행하는 일반적인 관행이 되었다.
- 출시 조율 엔지니어링은 빠르게 성장하고 제품, 서비스 변화율이 높은 기업에서 도입하면 도움이 될 것이다.

### 30장 - SRE를 이용해 운영 업무의 부담에서 벗어나기

- 1단계 : 서비스에 대해 배우고 컨텍스트 이해하기
    - 스트레스의 주범 규정하기
    - 문제 유발 가능한 부분을 규정하기
        - 지식의 차이 부분.. 대규모 팀에서 특정 사람들이 지나치게 전문화되면, 그 사람 때문에 다른 팀원들이 시스템 중요 부분에 무관심해질 수 있음
- 2단계 : 컨텍스트 공유
    - 팀을 위한 좋은 포스트모텀 문서 작성하기
    - 종류별로 긴급상황 구분하기
- 3단계 : 변화를 주도하기
    - SRE가 팀을 위해 할 수 있는 목표
    - (1) 서비스 수준 목표(SLO) 정하기
    - (2) 장애 원인 제거를 도와주기
    - (3) 이유를 설명하기 → SRE로서 결정한 것에 대한 이유와 구체적인 설명 필요
    - (4) 주도하는 질문을 하기
- SRE팀이 따라야 하는 원리에 대해 나왔던 장이었음.
