### ISSUE TITLE
Ch06 ~ Ch07

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/site-reliability-engineering#3]

**Comment by hhhyunwoo** [comment]
https://hhhyunwoo.github.io/posts/sre-ch6/
https://hhhyunwoo.github.io/posts/sre-ch7/

**Comment by jjangsungwon** [comment]
ch06: https://jjangsungwon.tistory.com/172
ch07: https://jjangsungwon.tistory.com/173

**Comment by ChanhuiSeok** [comment]
## 6장 분산 시스템 모니터링

모니터링과 알림

- 시스템에 언제 문제가 발생했는지 (이건 로그로도 남고), 어떤 문제가 발생하려 하는지 알 수 있음. → 실제로 이미 호출된 정보입니다 이런 오류가 떠서 확인해 보니, 사용자가 닉네임 변경 버튼을 하프뷰가 닫힐 때까지 계속 누른 로그가 찍혀 있었고 수정 코드가 나간 뒤에 고쳐진 것을 확인할 수 있었다.
- 잘못된 알림(노이즈) 비율을 낮게 유지하고, 올바른 알림의 비율을 높게 유지하려면 호출 담당 모니터링 시스템이 간결하면서도 안정적이어야 한다.

블랙박스, 화이트박스 모니터링

- 일단 이런 용어를 처음 들었다. 이 책을 통해 알게 되었다.
- 블랙박스 모니터링 : 서버 상에 나타나는 증상을 기본으로, 현재 이미 문제가 발생하는 상황을 모니터링
- 화이트박스 모니터링 : 로그, HTTP 종단점 등의 시스템 내부 동작들을 규범에 따라 살펴보는 모니터링.

둘을 구분해서 모니터링을 한다는 것을 알게 되었다. 이 부분이 명확할 필요가 분명 있는 것 같다.

그 외에 모니터링 시 고려해야 할 사항들

- 사용자를 대상으로 하는 시스템에서는 지연응답, 트래픽, 에러, 서비스 포화 상태를 중점적으로 체크해야 한다.
- 적당한 측정 방법을 선택한다. 시스템 지표들은 상황에 맞게 다른 수준으로 세분화하여 측정한다.
- 모니터링 시스템은 최대한 간결함을 추구하자.
- 제대로 구성된 모니터링과 알림 파이프라인은 간결하고 명료하다. 이는 증상 탐지에 집중할 수 있게 해 준다. 디버깅하고 원인 분석을 하면서 스스로 성장할 수 있는 기회도 제공한다.

## 7장 구글의 발전된 자동화

- 자동화의 가치 : 일관성, 플랫폼, 더 신속한 수리, 더 신속한 조치, 시간 절감
- 일관성 → 일관성의 가치를 최우선으로 추구. 일정하지 못한 방식은 실수, 간과로 인해 데이터 품질 문제 유발, 신뢰성 문제로 갈 수 있음
- 플랫폼 → 자동화된 시스템을 일컫는데, 실수를 중앙집중화 하는 데도 도움이 됨.
- 더 신속한 수리 → 시스템의 일반적 장애를 해결할 때 사용 가능. 평균 고장 후 수리 시간(MTTR) 절감 효과 기대 가능. 문제가 발생하자마자, 이를 알아내는 자동화된 시스템 도입
- 더 신속한 조치 → 수동으로 진행되는 운영 업무의 한계가 있음. 사람이 기계만큼 빠르게 대응하는 것이 대체로 불가능하기 때문.
- 시간 절감 → 자동화의 필요성 중 하나. 자동화 코드를 작성하는 데 드는 노력이 든다. (테스트 코드하고도 비슷하다는 느낌이 들었다.) 하지만 일단 자동화하면, 그 이후에는 시간 절감 효과를 누릴 수 있다.

구글은 자동화에 대한 강한 성향을 갖고 있다고 한다. 그리고 7장에서 설명이 나오는 자동화 시스템은 구글이 체계적이라는 인상을 심어주었다. 마지막에 나오는 말이 중요할 것 같다.

자동화든 뭐든 하려면 구글 정도의 규모가 되어야 하는 것 아니냐? 할 수 있는데 아니다. 자동화는 시간을 절약하는 것 이상의 가치를 제공하기 때문이다.

**Comment by ChanhuiSeok** [comment]
## 6장 분산 시스템 모니터링

모니터링과 알림

- 시스템에 언제 문제가 발생했는지 (이건 로그로도 남고), 어떤 문제가 발생하려 하는지 알 수 있음. 
- 잘못된 알림(노이즈) 비율을 낮게 유지하고, 올바른 알림의 비율을 높게 유지하려면 호출 담당 모니터링 시스템이 간결하면서도 안정적이어야 한다.

블랙박스, 화이트박스 모니터링

- 일단 이런 용어를 처음 들었다. 이 책을 통해 알게 되었다.
- 블랙박스 모니터링 : 서버 상에 나타나는 증상을 기본으로, 현재 이미 문제가 발생하는 상황을 모니터링
- 화이트박스 모니터링 : 로그, HTTP 종단점 등의 시스템 내부 동작들을 규범에 따라 살펴보는 모니터링.

둘을 구분해서 모니터링을 한다는 것을 알게 되었다. 이 부분이 명확할 필요가 분명 있는 것 같다.

그 외에 모니터링 시 고려해야 할 사항들

- 사용자를 대상으로 하는 시스템에서는 지연응답, 트래픽, 에러, 서비스 포화 상태를 중점적으로 체크해야 한다.
- 적당한 측정 방법을 선택한다. 시스템 지표들은 상황에 맞게 다른 수준으로 세분화하여 측정한다.
- 모니터링 시스템은 최대한 간결함을 추구하자.
- 제대로 구성된 모니터링과 알림 파이프라인은 간결하고 명료하다. 이는 증상 탐지에 집중할 수 있게 해 준다. 디버깅하고 원인 분석을 하면서 스스로 성장할 수 있는 기회도 제공한다.

## 7장 구글의 발전된 자동화

- 자동화의 가치 : 일관성, 플랫폼, 더 신속한 수리, 더 신속한 조치, 시간 절감
- 일관성 → 일관성의 가치를 최우선으로 추구. 일정하지 못한 방식은 실수, 간과로 인해 데이터 품질 문제 유발, 신뢰성 문제로 갈 수 있음
- 플랫폼 → 자동화된 시스템을 일컫는데, 실수를 중앙집중화 하는 데도 도움이 됨.
- 더 신속한 수리 → 시스템의 일반적 장애를 해결할 때 사용 가능. 평균 고장 후 수리 시간(MTTR) 절감 효과 기대 가능. 문제가 발생하자마자, 이를 알아내는 자동화된 시스템 도입
- 더 신속한 조치 → 수동으로 진행되는 운영 업무의 한계가 있음. 사람이 기계만큼 빠르게 대응하는 것이 대체로 불가능하기 때문.
- 시간 절감 → 자동화의 필요성 중 하나. 자동화 코드를 작성하는 데 드는 노력이 든다. (테스트 코드하고도 비슷하다는 느낌이 들었다.) 하지만 일단 자동화하면, 그 이후에는 시간 절감 효과를 누릴 수 있다.

구글은 자동화에 대한 강한 성향을 갖고 있다고 한다. 그리고 7장에서 설명이 나오는 자동화 시스템은 구글이 체계적이라는 인상을 심어주었다. 마지막에 나오는 말이 중요할 것 같다.

자동화든 뭐든 하려면 구글 정도의 규모가 되어야 하는 것 아니냐? 할 수 있는데 아니다. 자동화는 시간을 절약하는 것 이상의 가치를 제공하기 때문이다.
