### ISSUE TITLE
Ch11 ~ Ch13 (08.16)

### ISSUE THREAD

**Issue by jjangsungwon** [WhiteKow/site-reliability-engineering#5]

**Comment by ChanhuiSeok** [comment]
장애 조치, 비상 대기나 대응 등에 관한 내용들이었다.

## 11장 비상 대기

- 신뢰성, 가용성 위해 반드시 수행해야 할 중요 임무. 구글은 어떻게 운영하고 있나 나와 있었다. 주 대기조, 보조 대기조 등
- SRE 관리자 → 비상 대기 업무 부하를 균형 있게 관리하고, 업무 양과 품질 유지할 책임을 짐
- 비상 대기 업무에 대해 엔지니어들의 스트레스 등까지 세심하게 고려되어 있다는 점이 흥미로웠다. 이래서 구글인가?
- 중요한 점 : **분명한 장애 전파 경로 + 잘 정의된 장애 관리 프로세스 + ‘비난이 없는’ 포스트모텀 문화**
- SRE 팀이 너무 프로덕션 환경을 오래 접하지 못하는 일이 없도록 모든 엔지니어들이 최소 한두 분기마다 비상대기 업무에 투입되도록 조정, 모든 팀 구성원들이 프로덕션 환경에 적당히 노출되도록 한다.

## 12장 효과적인 장애 조치

- 장애 조치 과정
    - 문제 보고 → 장애 등급 선정 → 분석 → 진단 → 테스트 및 조치 → 장애 처리
    - 문제 보고 : 자동화된 장애 알림 혹은 동료가 말해주는 케이스. 일정한 양식으로 구성된 버그 추적 시스템 등 검색 가능한 위치에 저장되어야 한다. (깃허브 이슈탭이 비슷한 역할을 할 수 있지 않을까?)
    - 문제 우선순위 판단(영향도 판단) 및 관찰
- 와닿았던 부분 → 가장 마지막으로 수정된 부분에 주목. 무엇이 잘못되기 시작했다면, 가장 최근 변경한 부분에서 일어났을 확률이 큰 것 같다.
- 부정적인 결과의 마법 → 부정적 결과는 무시해서도 안 되고, 평가절하 해서도 안 된다. 스스로 잘못했다는 것을 인식하는 것은 엄청난 가치를 제공한다. (매우 공감. 문제가 있는 것을 회피하지 말고 빨리 처리하자)

## 13장 긴급 대응

- 시스템에 문제가 생겨도 → 당황하지 말자.

구글에서 겪었던 여러 장애 유형을 소개하고 있었다.

- 테스트로 인한 장애 (긴급 상황에 대한 사전적 테스트를 진행하고 있는데, 이 테스트를 진행하면서 실제 장애로 이어지는 경우에 대한 사례)
- 변경으로 인한 장애 - 철저한 카나리 테스트를 수행해야 할 필요성 대두
- 절차에 의한 장애 - 신속한 일 처리가 반드시 좋은 것만은 아니라는 것을 사례로 보여 줌
    - 시스템 종료 요청 연속적인 전달 이후 모든 서버에 디스크삭제 요청이 큐에 기록되면서 장애 발생
- 결국 중요한 것
    - 지난 일로부터 배우되 반복하지 말자
    - 장애에 대한 기록을 꼭 남기자
    - 만일 … 라면? 이라는 질문을 던지자
    - 사전 테스트를 장려하자

**Comment by jjangsungwon** [comment]
블로그 포스팅으로 대체합니다~!
- [비상 대기](https://jjangsungwon.tistory.com/179)
- [효과적인 장애 조치](https://jjangsungwon.tistory.com/180)
- [긴급 대응](https://jjangsungwon.tistory.com/181)

**Comment by hhhyunwoo** [comment]
https://hhhyunwoo.github.io/posts/sre-ch11/
https://hhhyunwoo.github.io/posts/sre-ch12/
