### ISSUE TITLE
Ch17 ~ Ch18

### ISSUE THREAD

**Issue by hhhyunwoo** [WhiteKow/site-reliability-engineering#7]

**Comment by jjangsungwon** [comment]
블로그 포스팅으로 대체합니다~!
- [신뢰성을 위한 테스트](https://jjangsungwon.tistory.com/186)
- [SRE 조직의 소프트웨어 엔지니어링](https://jjangsungwon.tistory.com/187)

**Comment by hhhyunwoo** [comment]
https://hhhyunwoo.github.io/posts/sre-ch17/

https://hhhyunwoo.github.io/posts/sre-ch18/

**Comment by ChanhuiSeok** [comment]
### 17장 신뢰성을 위한 테스트

- 사이트 신뢰성 엔지니어의 핵심 책임 중 하나 → 자신들이 관리하는 시스템에 대한 정량화된 신뢰도

전통적인 테스트

- 단위 테스트
- 통합 테스트
- 시스템 테스트
  - 스모크 테스트(가장 간단한 형태의 시스템 테스트, 안정성 검사로도 알려져 있음)
  - 성능 테스트
  - 회귀 테스트(이미 알려진 버그들을 통해 시스템의 실패나 잘못된 결과가 나타나는 것을 유추. 이 버그들을 테스트 형태로 작성해 두면, 이후 리팩토링 과정에서 이 버그들을 실수로 다시 만들어내는 일이 없을 것이다. -> 괜찮은 방법인데??)

프로덕션 테스트

- 실제 프로덕션 대상으로 이루어지는 테스트 → 블랙박스 모니터링과 유사하다. 기본적으로 수행해야 할 테스트이다.
- 설정 테스트, 스트레스 테스트, 카나리 테스트

결론 부분

- 테스트는 신뢰성 향상을 시킬 수 있는 가장 적절한 투자 수단이다. (테스트에 대한 강조사항은 익히 매번 들어서…)
- 테스트는 전체 주기 동안 한두 번에 끝낼 수 있는 행위가 아니고, 지속적인 행위이다.

---

### 18장 SRE 조직의 소프트웨어 엔지니어링
- SRE 조직도 소프트웨어 엔지니어링 역량이 중요하다.
- Auxon 사례에 대해 나온다.
    - Auxon : SRE가 구글 프로덕션 환경에서 실행되는 서비스의 수용량 계획을 자동화하기 위해 만든 도구
- 구글은 SRE의 경험을 바탕으로 소프트웨어를 개발하는 엔지니어의 덕을 톡톡히 보고 있다고 한다.
    - SRE에게 있어 경력 개발의 기회
    - 코딩 스킬이 녹스는 것을 원치 않는 엔지니어에게 고민의 탈출구
    - 등등… SRE가 자율적으로 진행하는 소프트웨어 개발 프로젝트가 SRE 조직에도 여러 가지 장점을 가져다 주었다고 함
