### ISSUE TITLE
Ch19 ~ Ch21

### ISSUE THREAD

**Issue by ChanhuiSeok** [WhiteKow/site-reliability-engineering#8]

**Comment by jjangsungwon** [comment]
블로그 포스팅으로 대체합니다~!
- [프론트엔드의 로드밸런싱](https://jjangsungwon.tistory.com/189)
- [데이터센터의 로드밸런싱](https://jjangsungwon.tistory.com/190)
- [과부하 처리하기](https://jjangsungwon.tistory.com/190)

**Comment by ChanhuiSeok** [comment]
## 19장 프런트엔드의 로드밸런싱

로드밸런싱에 대해 언급한 장이다.
- 특정 요청을 어느 데이터센터에 얼마나 많은 서버들이 처리할 것인지를 결정하기 위해 트래픽 로드밸런싱을 도입
- DNS를 이용한 로드밸런싱
    - 클라이언트가 HTTP 요청을 보내기 전에 DNS를 이용해 IP 주소를 먼저 조회하는데, 이 DNS 조회 과정에서 DNS 로드밸런싱 적용
- 가상 IP 주소(VIP)를 이용한 로드밸런싱
    - 일관된 해싱
    - 구글은 패킷 캡슐화를 사용 중
    

## 20장 데이터센터의 로드밸런싱

- 백엔드 태스크와 클라이언트 태스크
- 특정 서비스의 부하가 서비스 백엔드에 완벽히 퍼져서, 어느 한 시점에 가장 적은 부하를 처리하는 태스크와 가장 많은 부하를 처리하는 태스크의 CPU 사용률이 완전히 일치해야 함 → 골고루 퍼지게 한다는 의미
    - CPU 사용량이 없이 놀고 있으면 안 됨
- 양호하지 않은 태스크를 구별하는 방법 → 흐름 제어와 레임덕
    - 레임덕 상태가 무엇인지 몰랐는데, 백엔드 태스크가 세가지 중 하나의 상태로 나타낼 수 있었다.
    - 양호함 / 연결 거부 / 레임덕. 레임덕은 백엔드 태스크가 포트를 리스닝 중이며, 서비스를 제공할 수 있지만, 명시적으로 클라이언트에게 요청의 전달을 중단할 것을 요구하는 상태 라고 한다.
- 로드밸런싱 정책
    - 라운드 로빈
    - 최소 부하 라운드 로빈
    - 가중 라운드 로빈 → 위 두 가지 라운드 로빈에 비해, 백엔드가 제공하는 정보를 의사결정 프로세스에 반영하는 정책
        - 수용량 점수를 활용. 활용도, 쿼리 비율, 초당 에러율을 응답에 포함시키고 클라이언트는 백엔드가 현재 성공적으로 처리한 요청 수, 활용도 비용 등을 고려해 수용량 점수를 계속 갱신한다.
        - 실패한 요청은 향후 의사 결정에 불이익으로 작용한다.

## 21장 과부하 처리하기

- 로드밸런싱 정책의 목적 : 과부하를 피하기 위함
- **과부하 상태를 얼마나 잘 처리하는지가 시스템의 신뢰성을 확보하기 위한 기초임**
- 과부하를 처리하는 방식에 대해 몇 가지 소개하고 있었다.
    - 사용자별 제한하기 - 수용량 준비 및 사용자별 사용량 제한(보통 CPU)
    - 클라이언트 측에서의 사용량 제한
    - 중요도 → 해당 요청이 얼마나 중요한지에 따라
- 활용도에 대한 신호 → 가장 일반적인 신호는 프로세스의 ‘부하’ 임. 이것은 실행자 부하 평균 이라는 시스템에 의해 결정된다.
- 개별 태스크를 과부하로부터 보호하는 것이 중요하다.
- 과부하가 발생한 백엔드가 트래픽을 더 이상 받아들이지 못하는 상태라고 예상하면 매우 일반적인 실수이고, 견고한 로드밸런싱 목표에 치명타를 날릴 수가 있다고 한다.

**Comment by hhhyunwoo** [comment]
# [SRE] 19,20,21

# 19장 프런트엔드의 로드벨런싱

## 모든 일을 힘으로만 해결할 수는 없는 법

- 이상적이라면 트래픽은 여러 네트워크 링크, 데이터센터, 그리고 머신들에 최적화되어 분산되어야만 함.
- 최적화란?
    - 검색 결과에 있어서는 지연응답
    - 비디오 업로드에 있어서는 처리량
- 지역적 수준에서 볼 때, 구글에서는 어느 한 데이터센터 내에 배치된 모든 머신들은 사용자들과 동일한 거리만큼 떨어져있고, 동일한 네트워크에 연결되는 것으로 간주함.

## DNS를 이용한 로드벨런싱

- 몇 가지 문제들이 있지만, DNS는 사용자가 연결을 시작하기 전에 로드밸런싱을 수행할 수 있는 가장 간단하고 가장 효과적인 방법임
    - IP 주소의 재귀적 해석
    - 비결정적 응답 경로
    - 추가 캐시 지원

## 가상 IP 주소를 이용한 로드밸런싱

- VIP : 어느 특정 네트워크 인터페이스에 할당되지는 않음
- 로드밸런싱 방법
    - 1) 부하가 가장 적은 머신 선택
    - 2) 데이터 링크 계층 정보 조작
        - DSR 방법
    - 3) 패킷 캡슐화
        - 지금 구글이 사용하고 있음

# 20장 데이터센터의 로드밸런싱

- 외부에서 유입된 HTTP 요청이 HTTP 리버스 프록시 시스템인 GFE(Google Frontend) 에 전달되면 GFE 는 여러 알고리즘들을 활용해서 해당 요청을 처리할 수 있는 애플리케이션을 실행 중인 개별 프로세스로 요청의 payload 와 메타데이터를 라우팅함

## 양호하지 않은 태스크 구별하기

### 흐름제어

- 클라이언트 태스크들이 각각의 백엔드 태스크에 대한 연결별로 몇 개의 활성화된 요청을 전송했는지를 추적할 수 있다고 가정
- 활성화된 요청의 개수가 설정된 한계 값을 넘어서면 클라이언트는 백엔드가 양호하지 않은 상태에 있다고 가정 후 더 이상 요청을 전달하지 않음
- 하지만 태스크가 정말 양호하지 않은 상태에 있는지 아니면 단지 응답이 느린 것 뿐인지를 식별할 수 없음

### 레임덕

- 양호
    - 백엔드 태스크가 올바르게 요청들을 처리 중
- 연결 거부
    - 백엔드 태스크 응답 불가
- 레임 덕
    - 백엔드 태스크가 포트 리스닝 중이고 서비스 제공 가능하지만, 명시적으로 클라이언트에게 요청 전달 중단할 것을 요구

## 서브셋을 이용한 연결 풀 제한하기

- 서브셋을 통해서 클라이언트와 상호작용할 백엔드의 풀을 제한함

### 적절한 서브셋 선택하기

- 서브셋의 크기(얼마나 많은 백엔드가 클라에 연결될 것인지)를 선택해야함
- 20-100 으로 보통 정의

### 랜덤 서브셋

- 클라가 백엔드의 목록을 임의로 섞고 그중에서 접근이 가능하고 양호한 상태의 백엔드를 선택해서 서브셋 구축 하는 방법
- 균등하게 분산이 안됨

### 결정적  서브셋

- 구글의 해결책
- 클라이언트들을 라운드로 나누어 사용. 라운드에서 백엔드는 정확히 하나의 클라에 할당됨
- 이렇게 되면 실행 결과가 훨씬 더 좋아지고, 백엔드는 정확히 동일한 수의 연결을 처리할 수 있음

## 로드밸런싱 정책

### 간단한 라운드로빈

- 구현이 쉬움. 하지만 결과는 좋지 않음.
- 여러가지 요인에 영향받음
    - 작은 크기의 서브셋
    - 다양한 쿼리 비용
    - 머신의 다양성
    - 예측 불가능한 성능 요인들

### 최소 부하 라운드 로빈

- 가장 적은 수의 활성화된 요청을 처리하고 있는 태스크들만을 대상으로 라운드 로빈을 수행하는 것
- 만일 어느 태스크가 불안전하다면, 이 태스크는 100% 확률로 에러를 발생시킬 수 있음

### 가중 라운드 로빈

- 백엔드가 제공하는 정보를 의사결정 프로세스에 반영하는 중요한 정책
- 클라는 서브셋 내의 각 백엔드의 수용량을 점수 저장하고 있음. 이를 통해 가중치 계산

# 21장. 과부하 처리하기

- 로드밸런싱 정책이 얼마나 효율적이든 간에 결국 시스템의 일부는 과부하를 겪게되는데, 과부하 상태를 얼마나 잘 처리하는지는 시스템의 신뢰성을 확보하기 위한 기초임.

## 초당 쿼리 수의 함정

- 쿼리는 종류에 따라 요구하는 자원이 많이 다름.
- 단순 수가 아니라 자원에 대한 직접적인 수용량 측정을 할수도 있음. CPU, MEM

## 사용자별 제한

- 과부하에 시달리는 상황에서 어떤 작업에 우선순위를 둘 것인지를 결정하는 것
- 구글에서는 전역적인 사용량 정보를 모든 백엔드 태스크로부터 실시간 수집하고 데이터를 이용해서 개별 백엔드의 한계치를 효율적으로 제한함.
- 이를 위한 시스템이 있음.

## 클라이언트 측에서의 사용량 제한

- 고객의 자원 소비량이 할당량의 범위를 벗어나면 백엔드 태스크는 신속하게 이후의 요청을 거부해야함
