### ISSUE TITLE
Ch22

### ISSUE THREAD

**Issue by ChanhuiSeok** [WhiteKow/site-reliability-engineering#9]

**Comment by ChanhuiSeok** [comment]
# 22장 연속적 장애 다루기

- 연속적 장애 : 정상적인 것처럼 보여지는 응답 때문에 시간이 지나면서 장애가 가중되는 현상
- 연속적 장애를 유발하는 일반적인 원인
    - 과부하
        - 마치 도미노처럼 서비스 전체에 걸친 과부하 장애가 발생할 수 있음
    - 자원의 부족
        - 자원이 부족하면 어쩔 수 없이 장애 발생 가능
        - CPU나 메모리가 자원이 부족한 경우, 스레드 기아, 자원 간의 의존성 등에 의해 발생한다.
        - 파일 서술자가 부족해지면 네트워크 연결 초기화가 불가능해져 건강 상태 점검이 실패한다는 사실도 알게 되었다.
        - 자원이 부족하면 서버 충돌을 유발한다.
            - 컨테이너에 너무 많은 RAM이 할당되면 서버에서 충돌이 발생한다 ←

### 서버 과부하 방지하기

- 서버 수용량 한계에 대한 부하 테스트 + 과부하 상태에서의 실패에 대한 테스트
- 경감된 응답 제공
- 과부하 상태에서 요청을 거부하도록 서비스 구현
- 고수준 시스템들이 서버에 과부하 유발 않고 요청을 거부하도록 구현
    - 리버스 프록시, 로드밸런서(서비스가 과부하 상태 → 요청 스스로 차단하게 함)
- 수용량 계획 실행
    - 미리 성능 테스트를 병행해서 어느 수준의 부하에서 장애 발생하는지 판단 → 필요한 클러스터가 몇 개인지 대략 계획할 수 있음
    - 연속적 장애 발생 가능성을 줄여주긴 하지만, 이 장애로부터 시스템을 보호하는 데 큰 도움이 되지는 않음. (계획이고 예상치 못하게 장애가 발생한다면..) 그렇지만 이 계획은 반드시 필요함.
- 큐 관리하기
    - 보통 스레드 풀 앞에 배치된 큐가 가득 차면 서버는 새로운 요청을 거부함
    - 요청이 큐에 적재되면 더 많은 메모리 소비하고 지연응답이 증가하므로 (큐가 가득 차면 대부분의 시간을 큐에서 소비하게 되므로) 적절한 큐 크기 결정이 중요하다.
    - 지메일은 큐가 없는 서버를 이용한다고 한다. (→ 스레드 가득 차면, 다른 서버 태스크로 필요 작업을 이관)
- 부하 제한과 적절한 퇴보
    - 서버 과부하 상태 도달 → 부하 제한 → 유입 트래픽을 감소시킨다 → 부하를 덜어낼 수 있다
        - 일정 수 이상의 클라이언트 요청 유입 → 그 이후의 요청은 503 에러 리턴하는 것이 효과적인 대책 중 하나임
        - 선입선출 큐 → 후입선출 큐로 바꾸면 처리할 필요가 없는 요청들을 제거해서 부하를 줄일 수 있다. 보통 나중에 들어온 작업(요청)들을 거부하는 방향이라고 생각된다.
    - 적절한 퇴보는 **실행해야 할 작업의 양을 감소**시키는 방법.
        - 일부러 응답의 품질을 경감시켜, 작업 양이나 처리에 필요한 시간의 양을 줄일 수 있음
        - 예: 검색 애플리케이션 → 전체 DB가 아닌 메모리 캐싱된 일부 데이터만 검색 수행, 과부하 시 정확도는 떨어지나 더 빠른 순위 알고리즘 적용 등
- 재시도
    - 재시도에 관해서 이야기하고 있는데 결국 재시도 때문에 시스템 불안정을 초래할 수 있다는 의미
    - 백엔드로 재시도 요청을 할 때도 이런 주의사항이 있었구나 하는걸 깨달았다. (괜히 재시도 관련 가이드가 있는게 아니었구나 하는 생각)
    - 무한정 재시도하면 안된다고 했는데 그 최대 카운트가 있는 이유도 다시 한번 생각하게 되었다.
- 마감기한
    - 서버로 요청을 보냈고, 그 요청에 대한 응답을 프런트엔드가 기다릴 텐데… 마냥 클라이언트가 기다릴 수는 없으니 요청에 대한 마감기한을 설정하는 것을 의미한다. 마감 기한을 넘긴 요청은 의미가 없는 요청.
    - 서버들이 직접 마감 기한을 전파하고 작업의 취소를 전파하는 것이 권장된다.

### 느긋한 시작과 콜드 캐싱

- 막 시작된 직후는 안정적으로 동작하는 것에 비해 요청에 대한 응답이 상대적으로 느려지는 경향이 있음
    - 초기화가 필요한 경우
    - 일부 언어에서 런타임 성능 향상을 위한 추가 작업이 실행되는 경우
- 콜드 캐시를 갖는 경우 → 콜드 캐시 상태에서 요청을 처리하지 않으면 심각한 장애 위험에 놓일 수 있음
    - 콜드 캐시는 빈 캐시이거나 오래된 데이터로 채워져 있는 캐시이다. 캐시 히트율이 높지 않을 데이터들을 콜드 캐시로 보면 된다.
    - 새로운 클러스터를 켜거나(빈 캐시), 유지보수 후 클러스터를 서비스에 제공할 때(아마 변경된 사항이 있으니 기존에 캐시된 데이터가 유용하지 않다는 의미인 듯), 서비스 재시작(빈 캐시 상태 → 캐시를 채우는 데 어느 정도의 시간이 필요)

### 연속적 장애의 발생 요인

- 프로세스 중단, 프로세스 업데이트
    - 업데이트의 경우 새 버전을 배포할 때 많은 수에 태스크에 동시에 영향을 주면 연속적 장애를 유발할 수 있다고 한다. → 용량 계획 세우기, 가장 사용량이 많은 시점 피하기 등을 할 수 있음

결론 : 시스템 과부하로 연속적 장애가 발생할 수준에 도달하면 → **사용자 모든 요청을 완벽히 처리하기보다는 에러 리턴 혹은 평소보다 낮은 품질을 리턴해야 한다.**

**Comment by jjangsungwon** [comment]
[블로그 포스팅](https://jjangsungwon.tistory.com/193)으로 대체합니다~!

**Comment by hhhyunwoo** [comment]
# [SRE] 22장. 연속적 장애 다루기

**연속적 장애 (Cascading Failure)** 는 정상적인 것처럼 보여지는 응답때문에 시간이 지나면서 장애가 계속해서 가중되는 현상

## 연속적 장애의 원인과 그 대책

### 서버 과부하

- 가장 일반적 원인
- 한쪽으로 몰리게 되면 연속적인 장애를 야기할 수 있음

### 자원의 부족

- CPU 자원 부족
    - 주로 모든 요청의 처리가 느려짐.
    - 처리 중인 요청 수의 증가, 비정상적으로 증가하는 큐, Thread Starvation …
- 메모리 부족
    - 테스크 강제 종료, Java 의 GC 수행 증가 → CPU 사용 증가 (GC Death Spiral)…

## 서버 과부하 방지하기

- 서버 수용량 한계에 대한 부하 테스트 및 과부하 상태에서의 실패에 대한 테스트
- 경감된 응답 제공하기
- 과부하 상태에서 요청을 거부하도록 서비스 구현하기
- 고수준의 시스템들이 서버에 과부하를 유발하지 않고 요청을 거부하도록 구현하기
    - 리버스 프록시, LB를 통해 요청 차단 기능 구현
- 수용량 계획을 실행하기
    - 성능 테스트를 통해 정확한 값 계산이 필요

### 부하 제한과 적절한 퇴보

- 부하 제한 (Load Shedding) 을 통해 유입되는 트래픽을 감소시켜 어느정도의 부하를 덜어낸다
- 적절한 퇴보 (Graceful Degradation) 는 부하 제한의 개념에서 한 걸음 더 나아가 실행해야 할 작업의 양을 감소시키는 방법이다.
    - 일부러 일부 응답의 품질을 경감시켜 작업의 양이나 처리에 필요한 시간의 양을 현저히 줄임

### 재시도

- 백엔드가 요청을 처리하는데 많은 자원을 소모한다면 결국 과부하로 인해 요청 처리에 실패하게 되고 재시도 요청 떄문에 지속적으로 과부하 상태에 놓임

## 느긋한 시작과 콜드 캐싱

- 막 시작한 직후에는 조금 느릴 수 있음. 그 이유는 아래와 같음
    - 초기화가 필요한 경우 (웜업)
    - 일부 언어, 특히 자바의 경우 런타임 성능 향상을 위한 추가 작업이 실행되는 경우
    - 일부 바이너리들은 캐시가 채워져 있지 않으면 효율성이 떨어지는 경우도 있음
- 만약 캐시가 서비스에 중요한 영향을 미친다면…
    - 서비스를 Overprovision 한다.
    - 일반적인 연속적 장애 방지 기법을 적용한다.
    - 클러스터에 부하를 위임할 때 부하의 크기를 천천히 늘린다.

## 연속적 장애의 발생요인

### 프로세스 중단

- 일부 서버 태스크가 중단되어서 가용한 용량이 줄어든다.

### 프로세스 업데이트

### 새로운 배포

## 연속적 장애 테스트하기

### 장애가 발생할 때까지 테스트하고 조치하기

- 과부하 상태에서 서비스가 어떻게 동작하는지를 이해해야함.
- 그렇게 하기 위해서 장애를 발생시킨다. 컴포넌트가 장애가 생길 때까지 부하 테스트를 한다.
- 퇴보 모드에 들어간다면, 사람의 개입 없이 원래로 돌아올 수 있는지?
- 어느정도 부하가 절감되어야하는지?
- →
    - 천천히 테스크 수를 줄여본다
    - 클러스터 수용량을 조절
    - 시스템에서 백엔드를 감춰본다
    - 등으로 테스트 가능

## 연속적 장애를 처리하기 위한 즉각적인 대처

### 자원의 추가 투입

### 건강 상태 점검의 중지

- 헬스체크를 중단해서 다른 서비스들이 실행될 때까지 안정적으로 동작하도록 할 수 있음

### 서버의 재시작

- 죽음의 GC 소용돌이가 발생한 경우

### 퇴보 모드로 가지

### Batch Load 배제하기

### 문제가 있는 트래픽 배제하기
